### ISSUE TITLE
Velocity 3 compatibility

### ISSUE THREAD

**Issue by prototype464** [strifel/VBans#7]
This error is displayed in console upon booting up Velocity (3.0.0):

[18:43:13 ERROR]: Couldn't pass ProxyInitializeEvent to vbans
java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
        at de.strifel.vbans.VBans.onProxyInitialization(VBans.java:84) ~[?:?]
        at de.strifel.vbans.Lmbda$18.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:589) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:470) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by strifel** [comment]
Thanks for reporting this.
I did not have time to test it with Velocity 3, yet.
I will work on making a version for Velocity 3

**Comment by strifel** [comment]
Hi,
I am sorry that this takes so long.
I had and have a lot to do currently.

But I almost finished the changes today.
But it will take me a few more days to finish it. Sorry

**Comment by strifel** [comment]
[vbans-1.0-SNAPSHOT.jar.zip](https://github.com/strifel/VBans/files/7196254/vbans-1.0-SNAPSHOT.jar.zip)

Here is a first version 🎉  (needs to be unpacked, does contain bstats support)
I could not completely test it, yet.
@prototype464 could you test the new version and tell me if it works for you.

**Comment by pwnker** [comment]
I will test that build on my server, anything below velocity 3 is now unsupported so everyone needs to update to support 1.18 clients.

**Comment by pwnker** [comment]
As far as I can tell it seems to be working on velocity 3.1.0 without any issues. All the commands work as intended, the only thing that I noticed was that the error message returned when not giving enough args with a ban/kick command is white instead of the previous red.

**Comment by strifel** [comment]
Thanks for testing @pwnker
